default:
  view:
    edit_profile:
      icon_size: 20
max_file_size: 5
default_avatar: "profile_avatar.png"
allowed_image_file_type: ["image/png", "image/jpg", "image/jpeg", "image/gif"]
phone_number_regex: "\\A(\\+\\d{1,3}[- ]?)?\\d{10}\\z"
recommend_users_limit: 8
article_title_max_length: 255
user_item_avtar_size: [32, 32]
user_per_page: 8
article_per_page: 10
access_token_notfound: "Access token not found"
cache: 86400
msg:
  record_not_found: "Record not found"
  invalid_access_token: "Invalid access token"
  article_favorited: "Article favorited"
  article_unfavorited: "Article unfavorited"
  article_deleted: "Article deleted"
  comment_deleted: "Comment deleted successfully"
  follow_success: "Followed successfully"
  unfollow_success: "Unfollowed successfully"
  action_not_allowed: "You are not allowed to perform this action"
